name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Set Java version for Maven
      run: |
        echo "JAVA_HOME=$JAVA_HOME"
        echo "Using Java version:"
        java -version
        
    - name: Build with Maven
      run: mvn -B package --file demo/pom.xml
      
    - name: Test with Maven
      run: mvn -B test --file demo/pom.xml
      
    - name: Upload test results
      if: always()  # Always run this step, even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: demo/target/surefire-reports/
        retention-days: 5
